#! /bin/sh

path=$HOME/.opt/bin/

set -e
mkdir -p $path

for i in git-*; do
    rm -f $path/$i
    ln -s `pwd`/$i $path
done

rm -f $HOME/.gitconfig
ln -s `pwd`/.gitconfig $HOME/
ln -s `pwd`/.gitignore_global $HOME/
