#! /bin/sh

set -e

autoln () {
    if [ ! -f "$2/`basename $1`" ]; then
        echo link
        ln -s $1 $2
    fi
}

path=$HOME/.opt/bin/


mkdir -p $path

for i in bin/git-*; do
    rm -f $path/$i
    autoln `pwd`/$i $path
done

rm -f $HOME/.gitconfig

autoln "`pwd`/.gitconfig" $HOME/
autoln "`pwd`/.gitignore_global" $HOME/
